### PR TITLE
Remove Module tasklist

### LINKED ISSUE #77: bug(tasks): archive tasks not updating tasklist in module
Steps to reproduce:
1) Add a task
2) Archive it
3) Remove it
4) Task still counted in module tag & exists in `modulelist.json`

Reason: `isArchived` property of tasks in `Module`'s `taskList` isn't updated in `ArchiveTaskCommand::execute()` and `UnarchiveTaskCommand::execute()` so they don't pass the `.equals()` check during deletion and don't get deleted

Part of the problem with our current setup with two "sources of truth"

### PR DESCRIPTION
**Pull request by HoJunHao2000**
fix #77

### CODE REVIEW

File: src/main/java/modtrekt/logic/commands/RemoveTaskCommand.java [hunk 1]
```diff
@@ -12,22 +12,18 @@
...
 public class RemoveTaskCommand extends Command {
 
     public static final String COMMAND_WORD = "remove";
 
     public static final String MESSAGE_USAGE = COMMAND_WORD
             + ": Deletes the task/module identified by the index number.\n"
-            + "Parameters: " + CliSyntax.PREFIX_MODULE + ": Modules, " + CliSyntax.PREFIX_TASK + ": Tasks\n"
-            + "INDEX (must be a positive integer)\n"
-            + "Example: " + COMMAND_WORD + " " + CliSyntax.PREFIX_TASK + " 1";
+            + "Format: " + COMMAND_WORD + " " + CliSyntax.PREFIX_TASK + " <INDEX>";
```
Comment (domoberzin) [inline src/main/java/modtrekt/logic/commands/RemoveTaskCommand.java]: should we make this message the same as the one in `RemoveCommand`?

**Review by domoberzin — COMMENTED** [review]
LGTM, just the inconsistency between the usage message of RemoveCommand and RemoveTaskCommand

Good work!

File: src/main/java/modtrekt/logic/commands/RemoveTaskCommand.java (hunk 1 above)
Comment (HoJunHao2000) [reply src/main/java/modtrekt/logic/commands/RemoveTaskCommand.java]: done

**Review by domoberzin — APPROVED** [review]
