### PR TITLE
handle module parsing for failed HTTP requests

### LINKED ISSUE #143: add fallback data files for module fetching

### LINKED ISSUE #144: bug: errors in duplicate module name from save file
currently, having two modules with the same name, credit, and done status will result in an error reading from the saved modules file due to the equality check in the `JsonAdaptedModule` class, hence a duplicate module is detected.

Steps to replicate:
1) Add two modules with the same name and credits (CS1010S and CS1101S)
2) Close the app
3) Reopen the app

image

image

### PR DESCRIPTION
**Pull request by domoberzin**
Fallback data is saved in `modules.json` file. Only module titles and module credits are saved as we do not use the other information. File is only used in the event that the HTTP request to fetch the data fails.

### CODE REVIEW

File: src/main/java/modtrekt/logic/parser/module/ModuleParser.java [hunk 1]
```diff
@@ -34,13 +39,23 @@ private static Module sendGet(String code) throws IOException, InterruptedExcept
 
         HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());
```
Comment (jontmy) [inline src/main/java/modtrekt/logic/parser/module/ModuleParser.java]: The fallback does not work when the connection cannot be established (e.g. WiFi disabled) because a `java.net.ConnectionException` is thrown at this line, so there won't be a response to get the status code for.

`java.net.ConnectionException` is a subclass of `IOException` which means it gets caught by `AddModuleCommand`, which means this edge case was taken care of unintentionally.

Consequently, it'll instead throw a `CommandException` asking the user to use the verbose command - which I assume is unintended behavior as it should retrieve the module from the file.

**Review by jontmy — CHANGES_REQUESTED** [review]
Great work, but the command doesn't work when I disabled my WiFi - see the comment for more details.

File: src/main/java/modtrekt/logic/parser/module/ModuleParser.java (hunk 1 above)
Comment (domoberzin) [reply src/main/java/modtrekt/logic/parser/module/ModuleParser.java]: Good find! Will fix that

**Review by jontmy — APPROVED** [review]
